from bugfinder.models import Word2VecEmbeddingsBase
from bugfinder.models import Word2VecModel
from bugfinder.settings import LOGGER


#########################################
class Word2VecTraining(Word2VecModel):
    """Class responsible for the training of the Word2Vec model using the corpus generated by the tokenization of the dataset."""
    def init_model(self, name, **kwargs):
        """Class initialization method"""
        LOGGER.debug("Word2vec model class")


#########################################
class Word2VecEmbeddings(Word2VecEmbeddingsBase):
    """Class responsible for generating the embeddings using the Word2Vec model trained with the token's corpus."""
    def init_model(self, name, **kwargs):
        """Class initialization method"""
        LOGGER.debug("Word2vec embeddings class")
