import re
import glob
import networkx as nx
import subprocess
import shlex

from os import listdir
from os.path import join, split, splitext

from bugfinder.processing.tokenizers import main_func, keywords, AbstractTokenizer
from bugfinder.settings import LOGGER


class CombineDotFiles(AbstractTokenizer):
    """Processing to replace user-created functions from a dataset."""

    def execute(self):
        """Run the processing"""
        folder_processing_list = []

        for test_case_folder in self.dataset.test_cases:
            for dot_folder in listdir(join(self.dataset.path, test_case_folder)):
                if (
                    splitext(dot_folder)[1] in [".dot"]
                    and test_case_folder not in folder_processing_list
                ):
                    folder_processing_list.append(test_case_folder)

        while len(folder_processing_list) != 0:
            dot_folder = folder_processing_list.pop(0)
            LOGGER.info(
                "Combining DOT files in %s to a single file (%d items left)...",
                dot_folder,
                len(folder_processing_list),
            )

            self.process_file(join(self.dataset.path, dot_folder))

    @staticmethod
    def process_file(dot_folder):
        """Process a single folder looking for all .dot files generated by the CPG's
        analysis, and combine them in a single file for easier processing

        Args:
            dot_folder (str): Path of the folder containing the .dot files
            to be processed

        """
        complete_dot_file = "complete-cpg.dot"
        dotfiles = glob.glob(dot_folder + "/" + "*.dot")

        if len(dotfiles) == 0:
            LOGGER.info("No .dot files were found. Skipping this folder...")
            return

        LOGGER.info("%d DOT files found. Starting processing...", len(dotfiles))

        combined_dot_file = nx.MultiDiGraph()

        while len(dotfiles) != 0:
            dotfile = dotfiles.pop(0)
            dirpath, filepath = split(dotfile)

            if filepath == complete_dot_file:
                LOGGER.info("Combined DOT file found. Skipping this folder...")

                return

            LOGGER.debug("Processing %s (%d items left)...", dotfile, len(dotfiles))

            combined_dot_file = nx.compose(
                combined_dot_file, nx.drawing.nx_pydot.read_dot(dotfile)
            )

        dirpath, filepath = split(dotfile)
        out_file = join(dirpath, complete_dot_file)

        LOGGER.debug("Saving the combined DOT file on %s", out_file)

        try:
            with open(out_file, "wb") as f:
                nx.nx_pydot.write_dot(combined_dot_file, out_file)
        except Exception as e:
            LOGGER.error(e)
            LOGGER.error("Error while writing the normalized CPG to %s file", out_file)

    @classmethod
    def cpg_normalization(self, dotfile):
        LOGGER.debug("Processing %s", dotfile)
