import re
import glob
import networkx as nx
import subprocess
import shlex

from os import listdir
from os.path import join, split, splitext

from bugfinder.processing.tokenizers import main_func, keywords, AbstractTokenizer
from bugfinder.settings import LOGGER


class NormalizeCodePropertyGraph(AbstractTokenizer):
    """Processing to replace user-created functions from a dataset."""

    def execute(self):
        """Run the processing"""
        folder_processing_list = []

        for test_case_folder in self.dataset.test_cases:
            for dot_folder in listdir(join(self.dataset.path, test_case_folder)):
                if (
                    splitext(dot_folder)[1] in [".dot"]
                    and test_case_folder not in folder_processing_list
                ):
                    folder_processing_list.append(test_case_folder)

        while len(folder_processing_list) != 0:
            dot_folder = folder_processing_list.pop(0)
            LOGGER.info(
                "Starting CPG's normalization in %s (%d items left)...",
                dot_folder,
                len(folder_processing_list),
            )

            self.process_file(join(self.dataset.path, dot_folder))

    @staticmethod
    def process_file(dot_folder):
        """Process a single file looking for functions and variables in the DOT files
        generated by Joern, and replace them with a generic token. This normalization
        also includes replacing symbols combinations (<> replaced by ""), to avoid
        problems when processing the DOT file using networkx.

        Args:
            dot_folder (str): Path of the folder containing the DOT files
            to be processed

        """
        # tmp_dot_folder = "%s.tmp" % dot_folder

        sed_commands = [
            "sed -i -- 's/label = </label = \"/g' *.dot",
            "sed -i -- 's/> ]/\" ]/g' *.dot",
        ]

        NormalizeCodePropertyGraph.fix_dot_syntax(sed_commands, dot_folder)

        dotfiles = glob.glob(dot_folder + "/" + "*.dot")

        LOGGER.info("%d DOT files found. Starting normalization...", len(dotfiles))

        for dotfile in dotfiles:
            try:
                normalized_dotfile = NormalizeCodePropertyGraph.cpg_normalization(
                    dotfile
                )
            except Exception as e:
                LOGGER.error(e)
                normalized_dotfile = None

            if normalized_dotfile == None:
                LOGGER.error(
                    "Error while processing %s file! " + "File was not processed.",
                    dotfile,
                )
            else:
                dirpath, filepath = split(dotfile)
                # out_file = join (dirpath, ('processed-' + filepath))
                out_file = dotfile  # Replacing the old DOT file

                LOGGER.debug(
                    "Normalization done. Saving the new DOT file on %s", out_file
                )

                try:
                    with open(out_file, "wb") as f:
                        nx.nx_pydot.write_dot(normalized_dotfile, out_file)
                except Exception as e:
                    LOGGER.error(e)
                    LOGGER.error(
                        "Error while writing the normalized CPG to %s file", out_file
                    )

    @classmethod
    def cpg_normalization(self, dotfile):
        LOGGER.debug("Processing %s", dotfile)

        original_dot_graph = nx.drawing.nx_pydot.read_dot(dotfile)

        function_map = {}
        var_map = {}
        param_map = {}

        for node in original_dot_graph.nodes():
            if "label" in original_dot_graph.nodes[node]:
                original_dot_graph.nodes[node]["label"] = str(
                    original_dot_graph.nodes[node]["label"]
                ).replace("&lt;", "")
                original_dot_graph.nodes[node]["label"] = str(
                    original_dot_graph.nodes[node]["label"]
                ).replace("&gt;", "")
        for edge in original_dot_graph.edges(keys=True):
            if "label" in original_dot_graph.edges[edge]:
                original_dot_graph.edges[edge]["label"] = str(
                    original_dot_graph.edges[edge]["label"]
                ).replace("&lt;", "")
                original_dot_graph.edges[edge]["label"] = str(
                    original_dot_graph.edges[edge]["label"]
                ).replace("&gt;", "")

        node_attr = dict(nx.get_node_attributes(original_dot_graph, "label")).items()

        for id, label in node_attr:
            label_sections = str(label)[2:-2].split(")")[0].split(",")

            node_type = label_sections[0]

            if node_type == "METHOD":
                original_function_name = label_sections[1]

                if original_function_name[:8] != "operator":
                    function_map[original_function_name] = "FUN" + str(
                        len(function_map)
                    )

            elif node_type == "IDENTIFIER":
                original_variable_name = label_sections[1]

                if original_variable_name.upper() != "NULL":
                    if not original_variable_name in var_map.keys():
                        var_map[original_variable_name] = "VAR" + str(len(var_map))

            elif node_type == "PARAM":
                original_param_name = label_sections[1].split(" ")[-1]

                if not original_param_name in param_map.keys():
                    param_map[original_param_name] = "PARAM" + str(len(param_map))

        all_replacements = function_map | var_map | param_map
        for node in original_dot_graph.nodes():
            if "label" in original_dot_graph.nodes[node]:
                for original, normalized in all_replacements.items():
                    original_dot_graph.nodes[node]["label"] = str(
                        original_dot_graph.nodes[node]["label"]
                    ).replace(original, normalized)

        for edge in original_dot_graph.edges(keys=True):
            if "label" in original_dot_graph.edges[edge]:
                for original, normalized in all_replacements.items():
                    original_dot_graph.edges[edge]["label"] = str(
                        original_dot_graph.edges[edge]["label"]
                    ).replace(original, normalized)

        return original_dot_graph

    @classmethod
    def fix_dot_syntax(self, sed_commands, dot_folder):
        LOGGER.info("Running sed command on folder %s", dot_folder)

        for command in sed_commands:
            cmd_run_str = (
                "find " + dot_folder + ' -name "*.dot" -exec ' + command + " {} \\;"
            )

            try:
                res = subprocess.run(
                    shlex.split(cmd_run_str),
                    stdout=subprocess.DEVNULL,
                    stderr=subprocess.DEVNULL,
                )
            except subprocess.TimeoutExpired as e:
                LOGGER.error("Sub-process timed-out.")
            except subprocess.CalledProcessError as e:
                LOGGER.error(
                    "An error occurred when executing the command: %s", cmd_run_str
                )
                LOGGER.error("Return code: %d", e.returncode)
