image: python:3.9-slim

stages:
  - quality
  - tests
  - docs
  - pages

before_script:
  - pip install -r requirements.txt
  - pip install -r requirements.dev.txt
  - cd images; docker-compose build; cd - &>/dev/null

quality:
  stage: quality
  script:
    - black --check .
    - pylint ./bugfinder

tests:
  stage: tests
  script:
    - coverage run --source=bugfinder -m pytest ./tests
    - coverage report -m --fail-under=45

docs:
  stage: docs
  script:
    - cd docs
    - make html
  artifacts:
    paths:
      - dist/_docs/html

pages:
  stage: pages
  script:
    - mv dist/_docs/html public
  artifacts:
    paths:
      - public
