image: python:3.6

stages:
  - tests

before_script:
  - pip install -r ./requirements.txt
  - pip install -r ./requirements-dev.txt
  - cd images; docker-compose build

tests:
  stage: tests
  script: pytest


