version: "3.4"
services:
  neo4j:
    container_name: neo4j-ai
    image: neo4j:2.3.12
    environment:
      - NEO4J_CACHE_MEMORY=2048M
      - NEO4J_HEAP_MEMORY=2048
      - NEO4J_ALLOW_STORE_UPGRADE=true
      - NEO4J_AUTH=none
    ulimits:
      nproc: 65635
      nofile:
        soft: 60000
        hard: 60000
    ports:
      - 7474:7474
    volumes:
      - ${DATA_DIR}:/data/graph.db

