version: "3"
services:
  neo4j:
    image: "neo4j-ai:latest"
    environment:
      - NEO4J_dbms_memory_pagecache_size=4G
      - NEO4J_dbms_memory_heap_max__size=4G
      - NEO4J_dbms_allow__upgrade=true
      - NEO4J_dbms_shell_enabled=true
      - NEO4J_AUTH=none
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      #- "/home/delaitre2/Documents/ai-bugfinder/data/cwe121_annot/neo4j_v3.db:/data/databases/graph.db"
      - "/home/delaitre2/Documents/ai-bugfinder/data/aure/neo4j_v3.db:/data/databases/graph.db"
