version: "3"
services:
  joern-lite-v0.3.1:
    image: joern-lite:0.3.1
    build: ./joern-lite-v0.3.1
  joern-lite-v0.4.0:
    image: joern-lite:0.4.0
    build: ./joern-lite-v0.4.0
    environment:
      - NEO4J_dbms_memory_pagecache_size=24G
      - NEO4J_dbms_memory_heap_max_size=24G
      - NEO4J_wrapper_java_maxmemory=48G
      - NEO4J_dbms_routing_driver_connection_pool_max__size=20,
      - NEO4J_dbms_allow__upgrade=true
      - NEO4J_dbms_shell_enabled=true
      - NEO4J_dbms_transaction_timeout=2h
      - NEO4J_AUTH=none
      - EXTRA_JVM_ARGUMENTS=-Xmx48G
  neo4j-ai:
    image: neo4j-ai:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 1
      net.ipv6.conf.all.forwarding: 1
    build: ./neo4j-ai
  right-fixer:
    image: right-fixer:latest
    build: ./right-fixer
