version: "3"
services:
  neo4j:
    image: "neo4j-ai:latest"
    environment:
      - NEO4J_dbms_memory_pagecache_size=16G
      - NEO4J_dbms_memory_heap_max_size=16G
      - NEO4J_wrapper_java_maxmemory=32G
      - NEO4J_dbms_routing_driver_connection_pool_max__size=unlimited,
      - NEO4J_dbms_allow__upgrade=true
      - NEO4J_dbms_shell_enabled=true
      - NEO4J_dbms_transaction_timeout=2h
      - NEO4J_AUTH=none
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      #- "/home/user/Documents/ai-bugfinder/data/cwe121_small/neo4j_v3.db:/data/databases/graph.db"
      #- "/home/delaitre2/Documents/ai-bugfinder/data/cwe121_small/neo4j_v3.db:/data/databases/graph.db"
      - "/home/delaitre2/Documents/ai-bugfinder/data/ai-dataset/testsuite/neo4j_v3.db:/data/databases/graph.db"
      #- "/home/delaitre/Documents/ai-bugfinder/data/aure/neo4j_v3.db:/data/databases/graph.db"
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 1
      net.ipv6.conf.all.forwarding: 1
